### ISSUE TITLE
sphinx-build is not finding the install library

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/roundup-action#109]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

See action https://github.com/NASA-PDS/pds-api/actions/runs/4615069500/jobs/8158609883, line 229

### 🕵️ Expected behavior

I expected the sphinx-build to run

### 📜 To Reproduce

Trigger an unstable build on pds-api

### 🦄 Related requirements

🦄 #xyz

### ⚙️ Engineering Details

I am thinking the `sphinx-build` called by roundup is not running in the virtual environment where the dependencies have been installed. This is how I was able to reproduce that error locally, however I am not sure if roundup runs in a virtual environment.

**Comment by nutjob4life** [comment]
Ouch, this is a mess!

First, #79 re-installed Sphinx into the package being rounded up using `--ignore-installed` since Sphinx "comes with" the Roundup in the `github-actions-base`.

Then #105 we explicitly ignored the package's Sphinx because of version dependency issues in `pds-github-util`.

Now packages can't use Sphinx extensions like `sphinxcontrib.redoc`.

### Correct Fix

Undo the fix to #105 and break up `pds-github-util` so the parts used by Roundup (`python-release`, `maven-release`, and the Requirements reporter) are in separate packages without any Sphinx or Jinja2 dependencies.

### Quick Fix

Add `sphinxcontrib.redoc` to `github-actions-base`.

**Comment by nutjob4life** [comment]
The pull request for this fix [is in another repository](https://github.com/NASA-PDS/github-actions-base/pull/32).
