### ISSUE TITLE
Roundup DocsPublication step not working in maven

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#136]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I tagged a new release, the new docs were not pushed to gh-pages.

### 🕵️ Expected behavior

I expected the new documentation to be deployed

### 📜 To Reproduce

1. Tag a new release in https://nasa-pds.github.io/pds4-information-model/
2. Verify [stable release completes successfully](https://github.com/NASA-PDS/pds4-information-model/actions/runs/8636919328)
3. Verify the [documentation has not been updated online](https://nasa-pds.github.io/pds4-information-model/)
4. Verify the [gh-pages branch has not been updated](https://github.com/NASA-PDS/pds4-information-model/tree/gh-pages)

### 🖥 Environment Info

N/A

### 📚 Version of Software Used

stable

### ⚙️ Engineering Details

**Blocking https://github.com/NASA-PDS/pds4-information-model/issues/754**

Note: `i&t.skip` label applied because this is an internal automation bug. Workarounds exist but will very much delay our ability to tag new releases.

**Comment by jordanpadams** [comment]
@nutjob4life any idea what is going on here?

**Comment by nutjob4life** [comment]
Hi @jordanpadams. I only started investigating briefly on Friday. I expect to be able to devote more time to this once I can reproduce it in the sandbox.

**Comment by nutjob4life** [comment]
Notes:

- This is fixed by this [pull request in pds4-information-model](https://github.com/NASA-PDS/pds4-information-model/pull/757)
- Note that doc publication is suppressed for all Maven repositories by the [PDS-EN parent pom](https://github.com/NASA-PDS/pdsen-maven-parent) which has `<skip>true</skip>` and `<skipDeploy>true</skipDeploy>` in the `maven-site-plugin`
- Not sure this really has anything to do with `roundup-action`, but I'm leaving the issue here anyway 😉

**Comment by jordanpadams** [comment]
@nutjob4life closing this for now. I think this may be because if you have site setup both in your POM and in the parent POM, it will run both and their could be an issue? Idk. Whatever. Let's just leave this for now because I don't think we would explicitly skip it if it wasn't for a reason.

**Comment by nutjob4life** [comment]
Thanks @jordanpadams!
