### ISSUE TITLE
Enable specific Java Versions be specified in config

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/roundup-action#14]
**Is your feature request related to a problem? Please describe.**
I am pretty sure based upon the pds4-jparser failure that caused #13, that the reason for the failure is the ubuntu image used contains java11+, and pds4-jparser does not currently build with java11+.

it would be great if we could specify a specific version of Java in the roundup config. But we should investigate how much effort this would be and/or if it would make sense.

See this pds4-jparser Github Action run that was successful using the old snapshot workflow: https://github.com/NASA-PDS/pds4-jparser/runs/1420606307?check_suite_focus=true

**Comment by nutjob4life** [comment]
@jordanpadams I'm thinking about adding a `with` parameter to the action that lets you specify additional packages to install pre-roundup. The JDK package could appear here. This'll also help with a use-case @tloubrieu-jpl encountered with a package that used [numpy](https://numpy.org/) which had extra dependencies. Rather than include every possible dependency in the base Docker image for _every_ possible roundup, we can let specific roundups get them.

Also, I like how this issue was created 5 days ago, but was marked `delayed:1` 4 days ago. Sheesh! **I had just 1 day to complete it!?** You guys are rough! 😂

**Comment by jordanpadams** [comment]
@nutjob4life sounds great!

per the `delayed:1`, that was def a miscommunication between @tloubrieu-jpl and I. removed :-)

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life,

I am now having this error in pds-doi-service build:
Error: ***/roundup-action/master/action.yaml (Line: 35, Col: 7):
Error: ***/roundup-action/master/action.yaml (Line: 35, Col: 7): Unrecognized named-value: 'input'. Located at position 1 within expression: input.packages
Error: Fail to load ***/roundup-action/master/action.yaml

See https://github.com/NASA-PDS/pds-doi-service/runs/1448874081?check_suite_focus=true

It used to work. Do I need to add the packages option ? Which value should I have there ?

Thanks

**Comment by nutjob4life** [comment]
Looks like there is a single, missing letter `s`. 🙄
